---
- name: Install Docker and Jenkins
  hosts: webservers
  become: yes
  tasks:

  # Step 1: Install Prerequisites
  - name: Update apt and install prerequisites
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  # Step 2: Add Docker’s official GPG key and set up the stable repository
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Set up Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
      update_cache: yes

  # Step 3: Install Docker
  - name: Install Docker
    apt:
      name: docker-ce
      state: latest

  # Step 4: Install Docker Compose
  - name: Install Docker Compose
    vars:
      docker_compose_version: "1.29.2"
      os_type: "{{ ansible_os_family }}"
      arch: "{{ ansible_architecture }}"
    get_url:
      url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: '0755'

  # Step 5: Add user to docker group
  - name: Add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  # Step 6: Pull Jenkins Docker image
  - name: Pull Jenkins Docker image
    docker_image:
      name: jenkins/jenkins
      source: pull

  # Step 7: Create Jenkins container
  - name: Run Jenkins container
    docker_container:
      name: jenkins
      image: jenkins/jenkins
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - /var/jenkins_home:/var/jenkins_home
      restart_policy: always